### ISSUE TITLE
could you help me for your online3DViewer project ??

### ISSUE THREAD

**Issue by heningyuan6256** [X-Ryl669/freecadWebExport#3]
Your "online3DViewer" project has a branch named "cut plane." I'd like to know how to make it compatible with the latest version of "online3DViewer." Due to the ongoing updates in Three.js, it has now become an Object3D type. Could you provide me with an example? Thank you.

**Comment by X-Ryl669** [comment]
I've enabled the issue pane on the other repository. I invite you to post there so we can continue the discussion at the right place. Thanks
